---
version: '3.6'

services:
  nginx:
    image: nginx:latest
    container_name: nginx.local
    hostname: metrics.local
    restart: always
    volumes:
      - ./configs/nginx/:/etc/nginx/:ro
    ports:
      - "80:80"
    privileged: true

  grafana:
    image: grafana/grafana:9.5.1
    container_name: grafana.local
    hostname: grafana.local
    restart: always
    volumes:
      - ./configs/grafana/:/etc/grafana/:ro
    ports:
      - "3000:3000"

  prometheus:
    image: bitnami/prometheus
    container_name: prometheus.local
    hostname: prometheus.local
    restart: always
    volumes:
      - ./configs/prometheus:/opt/bitnami/prometheus/conf/:ro
    ports:
      - "9090:9090"
#    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter
    container_name: mysqld-exporter.local
    hostname: mysqld-exporter.local
    restart: always
    env_file:
      - mysqld-exporter.env
    environment:
      - DATA_SOURCE_NAME=${MYSQL_EXPORTER_USER}:MYSQL_EXPORTER_PASSWORD@(mysql.local:3306)/
    # volumes:
    #   - ./configs/grafana/:/etc/grafana/:ro

  mysql:
    image: mysql:5.7
    container_name: mysql.local
    hostname: mysql.local
    restart: always
    volumes:
      - ./configs/mysql/etcmysql/:/etc/mysql/:ro
      - ./configs/mysql/my.cnf:/etc/my.cnf:ro
      - ./configs/mysql/my.cnf.d/:/etc/my.cnf.d/:ro
      - ./mysqldb:/var/lib/mysql
    env_file:
      - mysql.env
      - mysqld-exporter.env
    ports:
      - "3306:3306"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
